Further expand array size support (#49)
This adds support for sizes identified as needed for post-quantum
KEM/DSA use cases, namely the ones from this comment:

https://github.com/RustCrypto/KEMs/pull/2#discussion_r1491883770

These should ideally get expanded into some consistent multiples above
1024, e.g. multiples of 32, and generated in a purely automated manner
(e.g. by a script that can break down the bit representation and build
the generic syntax), but this should at least be sufficient to unblock
these use cases.

Note that `UInt<UInt<..<UTerm, B#>, B#...` aliases expressing the
explicit bits for a given number are used instead of e.g. `<U1024 as
Add<U32>>::Output` because when the latter is used it causes similar
errors for conflicting trait impls as we saw with `typenum::U<N>` for
whatever reason:

error[E0119]: conflicting implementations of trait `traits::ArraySize`
for type `UTerm`
       --> src/sizes.rs:82:13
        |
    82  |               unsafe impl ArraySize for $ty {
        |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        |               |
        |               first implementation here
        |               conflicting implementation for `UTerm`