Add `Debug` bound to `ArraySize`
This came up with `elliptic-curve` and `sec1` as I was working on
`dhkem`:

error[E0277]: `<C as elliptic_curve::Curve>::FieldBytesSize` doesn't
implement `Debug`
  --> dhkem/src/ecdh_kem.rs:80:5
     |
     80 | /     fn encapsulate_with_rng<R: TryCryptoRng + ?Sized>(
     81 | |         &self,
     82 | |         rng: &mut R,
     83 | |     ) -> Result<(PublicKey<C>, SharedSecret<C>),
     Self::Error> {
        |
        |_____________________________________________________________^
        the trait `Debug` is not implemented for `<C as
        elliptic_curve::Curve>::FieldBytesSize`

`sec1::point::ModulusSize` bounds on `Debug`, but
`elliptic_curve::Curve::FieldBytesSize` does not. Yet for whatever
reason in `elliptic-curve` it's able to get away with:

    FieldBytesSize<C>: ModulusSize

Instead of adding a `Debug` bound to `Curve::FieldBytesSize` I thought I
would add it here instead to solve this problem for good.

This shouldn't be breaking, because `ArraySize` bounds on
`typenum::Unsigned`, which means it's impossible for 3rd party crates to
impl as they would need to add impls to a foreign type which isn't
allowed by the orphan rules.